# Site settings
title: 不忘初心，上下求索。
email: zzuieliyaoli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  前端ing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liyaoli.com" # the base hostname & protocol for your site
github_username:  zzuieliyaoli

# Build settings
markdown: kramdown
