# Site settings
title: 不忘初心，上下求索。
email: zzuieliyaoli@gmail.com
# description:>喜欢前端是因为：能够直接的把我认为的美，展现在大家面前。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liyaoli.com" # the base hostname & protocol for your site
github_username:  zzuieliyaoli
disqus: zzuieliyaoli
paginate: 5
paginate_path: "blog/page:num/"
# Build settings
markdown: kramdown
permalink: /:year-:month-:day/:title.html